services:
  # NOTE: Run 'npm run build' in the chatbot directory before starting containers
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload  # Enables auto-reload
    env_file:
      - ./api/.env
    volumes:
      - ./api/app:/app/app  # Mounts local files into the container
    ports:
      - "5000:5000"
