services:
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    working_dir: /chatbot
    ports:
      - "3001:5173"
    volumes:
      - ./chatbot:/chatbot
      - /chatbot/node_modules
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    working_dir: /dashboard
    ports:
      - "3002:5174"
    volumes:
      - ./dashboard:/dashboard
      - /dashboard/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload  # Enables auto-reload
    volumes:
      - ./api/app:/app/app  # Mounts local files into the container
    ports:
      - "5000:5000"
