version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload  # Enables auto-reload
    volumes:
      - ./api/app:/app/app  # Mounts local files into the container
    ports:
      - "5000:5000"
