services:
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    working_dir: /chatbot
    ports:
      - "3001:5173"
    volumes:
      - ./chatbot:/chatbot
      - /chatbot/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload  # Enables auto-reload
    env_file:
      - ./api/.env
    volumes:
      - ./api/app:/app/app  # Mounts local files into the container
    ports:
      - "5000:5000"
